default_language_version:
    python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
        args: ["--fix=lf"]

# TODO: Uncomment once ruff is added to this repo.
#  - repo: https://github.com/astral-sh/ruff-pre-commit
#    rev: v0.1.7
#    hooks:
#      # Run the linter.
#      - id: ruff
#        args: [ --fix ]
#      # Run the formatter.
#      - id: ruff-format