services:
  redis:
    image: redis:latest
    container_name: knowflow_redis

  postgres:
    image: postgres:latest
    container_name: knowflow_postgres
    env_file:
      - .envs/local/db.env
    volumes:
      - knowflow_postgres_volume:/var/lib/postgresql/data/

  server:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: local
    container_name: knowflow_api
    env_file:
      - .envs/local/api.env
      - .envs/local/db.env
    ports:
      - "8000:8000"
    volumes:
      - ./:/code:z
    restart: always
    depends_on:
      - postgres
      - redis
    
  celery:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: local
    container_name: knowflow_celery
    env_file:
      - .envs/local/api.env
      - .envs/local/db.env
    volumes:
      - ./:/code:z
    entrypoint: ["python", "-m", "celery", "-A", "knowflow", "worker", "-l", "info"]
    depends_on:
      - redis
  
  chroma:
    image: chromadb/chroma:latest
    container_name: knowflow_chroma
    ports:
      - "8001:8001"
    volumes:
      - knowflow_chroma_volume:/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma
    command: run --host 0.0.0.0 --port 8001
    restart: unless-stopped


volumes:  
  knowflow_postgres_volume:
  knowflow_chroma_volume: