# Generated by Django 5.0.7 on 2025-07-19 09:23

import apps.file.utils
import knowflow.configurations.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(storage=knowflow.configurations.storage_backend.MediaStorage(), upload_to='documents/', validators=[apps.file.utils.validate_file_extension])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
